spring:
  datasource:
    url: jdbc:mysql://localhost:3308/test
    username: root
    password: root
  liquibase:
    change-log: classpath:/db/changelog/app-changelog.xml
    default-schema: test
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt:
  SECRET_KEY: "vNfCm9KVZBmnU2jqw1p+/vXTuivS2mHdChK4yZZbCbY="
  EXPIRATION_TIME: 86400000
